# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('nonmember', 'Nonmember'), ('member', 'Member'), ('alumnus', 'Alumnus')], default='unknown', max_length=20, verbose_name='Membership status'),
        ),
        migrations.AddField(
            model_name='member',
            name='status_changed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
