# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='Enter the name of the section', max_length=255, verbose_name='English section name')),
                ('name_sv', models.CharField(help_text='Enter the name of the section', max_length=255, verbose_name='Swedish section name')),
                ('abbreviation', models.CharField(blank=True, help_text='Enter the abbreviation for the section', max_length=130, null=True, verbose_name='Section abbreviation')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.AlterModelOptions(
            name='studyprogram',
            options={'verbose_name': 'study program', 'verbose_name_plural': 'study programs'},
        ),
        migrations.AddField(
            model_name='section',
            name='studies',
            field=models.ManyToManyField(blank=True, related_name='sections', to='members.StudyProgram'),
        ),
    ]
