# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170404_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='abbreviation_en',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='abbreviation_sv',
        ),
    ]
