# Generated by Django 2.1.7 on 2019-07-30 09:19

from django.db import migrations, models
from members.models import Member

def nullify_columns(apps, schema_editor):
	for member in Member.objects.all():
		member.first_name = ''
		member.last_name = ''
		member.phone_number = ''
		member.birthday = None
		member.person_number_ext = ''
		member.email = ''
		member.status = ''
		member.save()

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180605_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='melos_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
		migrations.RunPython(nullify_columns),
		migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, null=True, default='', max_length=130),
        ),
		migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, null=True, default='', max_length=130),
        ),
		migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, null=True, default='', max_length=130),
        ),
		migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, null=True, default='', max_length=130),
        ),
    ]
