# Generated by Django 2.2.2 on 2019-12-03 13:47

import django.core.validators
from django.db import migrations, models
import members.models.member


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_melos_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', members.models.member.MelosUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='person_number_ext',
            field=models.CharField(blank=True, help_text='Enter the last four digits of your Swedish person number, given by the Swedish tax authority', max_length=4, null=True, unique_for_date='birthday', validators=[django.core.validators.RegexValidator(message='The person number extension consists of four numbers', regex='^\\d{4}$')], verbose_name='Person number extension'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Enter a phone number so UTN may reach you', max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('nonmember', 'Nonmember'), ('member', 'Member'), ('alumnus', 'Alumnus')], default='unknown', max_length=20, verbose_name='Membership status'),
        ),
    ]
