# Generated by Django 2.2.2 on 2019-12-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20191203_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='melos_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]