# Generated by Django 2.2.2 on 2019-12-18 09:55

from django.db import migrations, models
import members.models.member


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20191206_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status_changed',
            field=models.DateTimeField(default=members.models.member.status_changed_default),
        ),
    ]
