# Generated by Django 2.2.8 on 2019-12-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20191218_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(help_text='Enter an email adress so UTN may reach you', max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(help_text='Enter a phone number so UTN may reach you', max_length=20, verbose_name='Phone number'),
        ),
    ]
