# Generated by Django 3.1.4 on 2020-12-17 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20200106_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='person_number_ext',
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='member',
            name='person_nr',
            field=models.CharField(blank=True, max_length=13, verbose_name='Person number'),
        ),
        migrations.AddField(
            model_name='member',
            name='user_info_expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
