# Generated by Django 3.1.4 on 2020-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20201217_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='person_nr',
            field=models.CharField(max_length=13, verbose_name='Person number'),
        ),
    ]
