# Generated by Django 3.2.17 on 2023-11-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20201217_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='melos_id',
            new_name='unicore_id',
        ),
    ]
