language: python
python:
  - "3.5"
  - "3.6"
install:
- pip install -r dev-requirements.txt
- pip install coveralls
script:
  - flake8 src
  - coverage run --source='.' ./src/manage.py test src
after_success:
  coveralls
notifications:
  slack: utnkar:yoXuou43TNbtRLmeIyga5mmO