language: python
python:
  - "3.5"
  - "3.6"
install: "pip install -r dev-requirements.txt"
script:
  - flake8 website
  - ./website/manage.py test website
notifications:
  slack: utnkar:yoXuou43TNbtRLmeIyga5mmO