# Generated by Django 2.2.13 on 2020-08-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramfeed',
            name='id',
        ),
        migrations.AlterField(
            model_name='instagramfeed',
            name='account_name',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
