# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('involvement', '0002_role_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='approval_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Approval committee'),
        ),
    ]
