# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0003_position_approval_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='approval_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='involvement.Team', verbose_name='Approval committee'),
        ),
    ]
