# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0004_auto_20170330_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'default_permissions': (), 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'default_permissions': (), 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': (), 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'default_permissions': (), 'permissions': (('admin', 'Can administrate the recruitment process'),), 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
