# Generated by Django 2.2.13 on 2020-08-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0003_footersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=80)),
                ('access_token', models.CharField(max_length=500)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Instagram Feed',
                'verbose_name_plural': 'Instagram Feeds',
            },
        ),
    ]
