# Generated by Django 2.2.13 on 2020-08-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_instagram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagram',
            options={'verbose_name': 'Instagram', 'verbose_name_plural': 'Instagram'},
        ),
    ]
