# Generated by Django 3.2.17 on 2023-03-01 18:25

from django.db import migrations
from django.db.models import F
from utils.data_migrations import stream_field_filter_map

# def del_footer_sv()


def copy_field(apps, schema):
    MyModel = apps.get_model('branding', 'footersettings')
    MyModel.objects.all().update(footer_sv=F('footer_en'))
    
class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_footer_sv'),
    ]

    operations = [migrations.RunPython(copy_field),
    ]
