# Generated by Django 3.2.17 on 2023-08-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0005_fix_empty_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'footer_en'},
        ),
    ]
