# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyprogram',
            old_name='abbreviation',
            new_name='abbreviation_en',
        ),
        migrations.RenameField(
            model_name='studyprogram',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='abbreviation_sv',
            field=models.CharField(blank=True, help_text='Enter the abbreviation for the study program', max_length=130, null=True, verbose_name='Study program abbreviation'),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='name_sv',
            field=models.CharField(default='X', help_text='Enter the name of the study program', max_length=255, verbose_name='Study program name'),
            preserve_default=False,
        ),
    ]
