# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170214_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='abbreviation_en',
            field=models.CharField(blank=True, help_text='Enter the abbreviation for the study program', max_length=130, null=True, verbose_name='English program abbreviation'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='abbreviation_sv',
            field=models.CharField(blank=True, help_text='Enter the abbreviation for the study program', max_length=130, null=True, verbose_name='Swedish program abbreviation'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='name_en',
            field=models.CharField(help_text='Enter the name of the study program', max_length=255, verbose_name='English program name'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='name_sv',
            field=models.CharField(help_text='Enter the name of the study program', max_length=255, verbose_name='Swedish program name'),
        ),
    ]
