# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title_en', models.CharField(blank=True, help_text='Enter the title to be shown on the banner.', max_length=255, verbose_name='English banner title')),
                ('title_sv', models.CharField(blank=True, help_text='Enter the title to be shown on the banner.', max_length=255, verbose_name='Swedish banner title')),
                ('text_en', models.TextField(blank=True, help_text='Enter a text to be shown on the banner.', verbose_name='English banner text')),
                ('text_sv', models.TextField(blank=True, help_text='Enter a text to be shown on the banner.', verbose_name='Swedish banner text')),
                ('link', models.URLField(blank=True, verbose_name='Button URL')),
                ('button_en', models.TextField(blank=True, help_text='Enter the text to be displayed on the button.', verbose_name='English button text')),
                ('button_sv', models.TextField(blank=True, help_text='Enter the text to be displayed on the button.', verbose_name='Swedish button text')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_en',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.CharBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image_description', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('icons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('icon', wagtail.core.blocks.CharBlock(help_text='Material icon font icon text, as found on: https://material.io/icons')), ('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock()))))), ('hide_on_med', wagtail.core.blocks.BooleanBlock(required=False))))), ('image_icons', wagtail.core.blocks.StructBlock((('description', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('hide_on_med', wagtail.core.blocks.BooleanBlock(required=False))))), ('overlay', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('button', wagtail.core.blocks.CharBlock(required=False))))), ('logos', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='fa-pied-piper', label='Logos', template='blocks/logos.html')), ('counters', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('counters', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('icon', wagtail.core.blocks.CharBlock(help_text='Material icon font icon text, as found on: https://material.io/icons')), ('value', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock(required=False)))))), ('style', wagtail.core.blocks.ChoiceBlock(choices=[('light', 'Light'), ('dark', 'Dark')]))))), ('image', wagtail.images.blocks.ImageChooserBlock(template='blocks/image.html'))), blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_sv',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.CharBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image_description', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('icons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('icon', wagtail.core.blocks.CharBlock(help_text='Material icon font icon text, as found on: https://material.io/icons')), ('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock()))))), ('hide_on_med', wagtail.core.blocks.BooleanBlock(required=False))))), ('image_icons', wagtail.core.blocks.StructBlock((('description', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('hide_on_med', wagtail.core.blocks.BooleanBlock(required=False))))), ('overlay', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('button', wagtail.core.blocks.CharBlock(required=False))))), ('logos', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='fa-pied-piper', label='Logos', template='blocks/logos.html')), ('counters', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('counters', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('icon', wagtail.core.blocks.CharBlock(help_text='Material icon font icon text, as found on: https://material.io/icons')), ('value', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock(required=False)))))), ('style', wagtail.core.blocks.ChoiceBlock(choices=[('light', 'Light'), ('dark', 'Dark')]))))), ('image', wagtail.images.blocks.ImageChooserBlock(template='blocks/image.html'))), blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_sv',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='home.HomePage'),
        ),
    ]
