# Generated by Django 2.1.7 on 2019-07-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20181229_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_searchbar',
            field=models.BooleanField(default=True),
        ),
    ]
