# Generated by Django 2.1.11 on 2019-10-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20191003_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='add_whitespace_bottom',
            field=models.BooleanField(default=True),
        ),
    ]
