# Generated by Django 2.2.2 on 2019-11-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20181001_1949'),
        ('home', '0020_homepage_add_whitespace_bottom'),
    ]

    operations = [
    ]
