# Generated by Django 2.2.2 on 2019-12-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20191203_1447'),
        ('home', '0021_auto_20191111_1806'),
    ]

    operations = [
    ]
