# Generated by Django 2.2.9 on 2020-02-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('home', '0024_auto_20191230_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='featured_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
    ]
