# Generated by Django 2.2.9 on 2020-02-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200207_1359'),
        ('home', '0026_auto_20200211_1859'),
    ]

    operations = [
    ]
