# Generated by Django 2.2.10 on 2020-04-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200404_2152'),
        ('home', '0043_auto_20200404_2005'),
    ]

    operations = [
    ]
