# Generated by Django 2.2.13 on 2020-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20201023_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='use_recaptcha',
            field=models.BooleanField(default=False, verbose_name='Use Recaptcha'),
        ),
    ]
