# Generated by Django 3.1.2 on 2020-10-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20201023_1815'),
        ('home', '0046_auto_20201023_1517'),
    ]

    operations = [
    ]
