# Generated by Django 3.1.7 on 2021-04-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20210401_1343'),
        ('home', '0050_auto_20210406_1427'),
    ]

    operations = [
    ]
