# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('involvement', '0008_auto_20170502_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_en', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='English Description')),
                ('description_sv', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Swedish Description')),
                ('name', models.CharField(blank=True, help_text='Overrides account name of position holder of the selected role.', max_length=100, verbose_name='Name')),
                ('role_text_en', models.CharField(blank=True, help_text='Overrides role name from the selected role.', max_length=100, verbose_name='English Role Name')),
                ('role_text_sv', models.CharField(blank=True, help_text='Overrides role name from the selected role.', max_length=100, verbose_name='Swedish Role Name')),
                ('email', models.EmailField(blank=True, help_text='Overrides account email address of position holder of the selected role.', max_length=254, verbose_name='Email address')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('role', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_cards', to='involvement.Role')),
            ],
        ),
    ]
