# Generated by Django 2.0.5 on 2018-06-05 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('involvement', '0009_contactcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_from', models.DateField(verbose_name='Date of appointment')),
                ('term_to', models.DateField(verbose_name='End date of appointment')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandate_history', to='involvement.Position')),
            ],
            options={
                'verbose_name': 'Mandate history',
                'verbose_name_plural': 'Mandate histories',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='mandatehistory',
            unique_together={('position', 'applicant', 'term_from', 'term_to')},
        ),
    ]
