# Generated by Django 2.0.5 on 2018-06-07 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('involvement', '0010_auto_20180605_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_mandate', to='involvement.Position')),
            ],
            options={
                'verbose_name': 'Current mandate',
                'verbose_name_plural': 'Current mandates',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='currentmandate',
            unique_together={('position', 'applicant')},
        ),
    ]
