# Generated by Django 2.0.5 on 2018-06-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0011_auto_20180607_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentmandate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_mandates', to='involvement.Position'),
        ),
        migrations.AlterField(
            model_name='mandatehistory',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandate_histories', to='involvement.Position'),
        ),
    ]
