# Generated by Django 2.0.5 on 2018-06-11 15:12

from django.db import migrations
from django.contrib.auth.models import Group
from involvement.models import Role

def populate_groups(apps, schema_editor):
	Group.objects.all().delete()
	for role in Role.objects.all():
		group_name = role.name[:80]
		group, created = Group.objects.get_or_create(name=group_name)
		if created:
			group.save

		role.group = group
		role.save()

class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0013_connect_group_to_role'),
    ]

    operations = [
    	migrations.RunPython(populate_groups),
    ]
