# Generated by Django 2.0.5 on 2018-06-19 12:13

from django.db import migrations
from django.contrib.auth.models import Group
from involvement.models import Role, ContactCard, Reference, \
	Application, MandateHistory, Position


def remove_deps(apps, schema_editor):
	Group.objects.all().delete()
	ContactCard.objects.all().delete()
	Reference.objects.all().delete()
	Application.objects.all().delete()
	MandateHistory.objects.all().delete()
	Position.objects.all().delete()
	Role.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0013_connect_group_to_role'),
    ]

    operations = [
    	migrations.RunPython(remove_deps),
    ]
