# Generated by Django 2.0.5 on 2018-06-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0014_populate_role_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='auth.Group'),
        ),
    ]
