# Generated by Django 2.0.5 on 2018-06-12 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('involvement', '0015_auto_20180611_1741'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currentmandate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='currentmandate',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='currentmandate',
            name='position',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': (), 'permissions': (('admin', 'Admin'), ('fum', 'FUM'), ('board', 'Board'), ('presidium', 'Presidium'), ('group_leader', 'Group Leader'), ('engaged', 'Engaged')), 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterUniqueTogether(
            name='mandatehistory',
            unique_together={('position', 'applicant')},
        ),
        migrations.RemoveField(
            model_name='mandatehistory',
            name='term_from',
        ),
        migrations.RemoveField(
            model_name='mandatehistory',
            name='term_to',
        ),
        migrations.DeleteModel(
            name='CurrentMandate',
        ),
    ]
