# Generated by Django 2.0.5 on 2018-06-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0016_auto_20180612_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='approval_committee',
        ),
    ]
