# Generated by Django 2.0.5 on 2018-06-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0017_remove_position_approval_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcard',
            name='role',
        ),
        migrations.AddField(
            model_name='contactcard',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_card', to='involvement.Application'),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_cards', to='involvement.Position'),
        ),
    ]
