# Generated by Django 2.0.5 on 2018-06-13 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0017_remove_position_approval_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter a phone number to contact this role', max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?\\d+$')], verbose_name='Phone number'),
        ),
    ]
