# Generated by Django 2.1.7 on 2019-08-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0020_auto_20180628_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejection_date',
            field=models.DateField(null=True, blank=True, verbose_name='Rejection date'),
        ),
    ]
