# Generated by Django 3.1.7 on 2021-05-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0022_auto_20200127_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(help_text='Present yourself and state why you are who we are looking for', verbose_name='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='application',
            name='qualifications',
            field=models.TextField(help_text='Give a summary of relevant qualifications', verbose_name='Qualifications'),
        ),
    ]
