# Generated by Django 3.2.3 on 2022-05-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0024_auto_20210512_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='gdpr',
            field=models.BooleanField(default=False, help_text='GDPR text...', verbose_name='GDPR'),
        ),
    ]
