# Generated by Django 3.2.3 on 2022-11-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0032_alter_application_gdpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gdpr',
            field=models.BooleanField(default=False, help_text='I accept that my data is saved in accordance with Uppsala Union of Engineering and Science Students integrity policy that can be found at<a> https://www.utn.se/about-union/document-archive/</a>', verbose_name='GDPR'),
        ),
    ]
