# Generated by Django 3.2.3 on 2023-02-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0046_alter_application_gdpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gdpr',
            field=models.BooleanField(default=False, help_text='\n            I accept that my data is saved in accordance\n            with Uppsala Union of Engineering and Science Students integrity\n            policy that can be found within the link:\n        ', verbose_name='GDPR'),
        ),
    ]
