# Generated by Django 3.2.17 on 2023-03-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0047_auto_20221114_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(help_text='Present yourself and state why you are\n         who we are looking for', verbose_name='Cover Letter'),
        ),
    ]
