# Generated by Django 3.2.17 on 2023-02-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0047_alter_application_gdpr'),
    ]

    operations = [
    ]
