# Generated by Django 3.2.17 on 2023-03-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('involvement', '0047_alter_application_gdpr'),
        ('involvement', '0048_alter_application_cover_letter'),
    ]

    operations = [
    ]
