# Generated by Django 3.2.3 on 2021-09-21 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a descriptive event name', max_length=255, verbose_name='Name of event')),
                ('description', models.CharField(help_text='Enter a description for the event', max_length=1000, verbose_name='Description for event')),
                ('start_date', models.DateField(help_text='Event start date', verbose_name='Time and date when the event starts')),
                ('end_date', models.DateField(help_text='Event end date', verbose_name='Time and date when the event ends')),
                ('tickets_number', models.IntegerField(verbose_name='Number of entries')),
                ('removed', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField(verbose_name='Ticket number')),
                ('removed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'default_permissions': (),
            },
        ),
    ]
