# Generated by Django 3.2.3 on 2021-09-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_permissions': (), 'ordering': ['title'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets_number',
        ),
        migrations.AddField(
            model_name='event',
            name='num_tickets',
            field=models.IntegerField(default=1, help_text='This dictates the number of individual entries to the event.', verbose_name='Number of entries'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='num_extra_participants',
            field=models.IntegerField(default=0, help_text='Dictates the number of participants in the ticket besides the ticket owner.', verbose_name='Extra participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='This is the long text shown as description for the event.', max_length=1000, verbose_name='Description for event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='This dictates when the event is considered finished.', verbose_name='Event end time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Recommended size of TODO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='This dictates when the event is considered as ongoing.', verbose_name='Event start time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='This is the display name for the event', max_length=255, verbose_name='Name of event'),
        ),
    ]
