# Generated by Django 3.2.3 on 2021-09-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210921_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This field identifies the cost list.', max_length=255, verbose_name='Cost list name')),
                ('fields', models.JSONField(help_text='These fields determine what _each_ participant can purchase. They each need their name (key) and field type.', verbose_name='Purchaseable items')),
            ],
            options={
                'verbose_name': 'Costs',
                'verbose_name_plural': 'Costs',
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
    ]
