# Generated by Django 3.2.3 on 2021-09-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_list',
            field=models.ForeignKey(blank=True, help_text='The price list for each participant', null=True, on_delete=django.db.models.deletion.PROTECT, to='events.costs', verbose_name='Price list'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='fields',
            field=models.JSONField(help_text='These fields determine what each participant can purchase. They each need their name (key) and field type.', verbose_name='Purchaseable items'),
        ),
    ]
