# Generated by Django 3.2.3 on 2022-01-20 18:36

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220120_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=wagtail.core.fields.RichTextField(help_text='This is the long text shown as description for the event.', max_length=1000, verbose_name='Description for event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='info_for_participants',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='This separate information will be presented to those who recieve tickets.', max_length=1000, null=True, verbose_name='Information for participants'),
        ),
    ]
