# Generated by Django 3.2.3 on 2022-02-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220120_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='raffle_has_been_held',
            field=models.BooleanField(default=False, help_text='This signals to users whether a raffle has been held. This field populates automatically once a raffle has been held.', verbose_name='Raffle has been held'),
        ),
    ]
