# Generated by Django 3.2.3 on 2021-11-16 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20210930_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='first_come_first_serve',
            field=models.BooleanField(default=False, help_text='Immediately assign applicants first-come-first-serve. Not suitable for events that raffle their entries.', verbose_name='First come first serve'),
        ),
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
                ('event_applicant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'default_permissions': (),
            },
        ),
    ]
