# Generated by Django 3.2.3 on 2021-11-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_ticket_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventapplication',
            options={'default_permissions': (), 'verbose_name': 'Event Application', 'verbose_name_plural': 'Event Applications'},
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This field identifies the participant type.', max_length=255, verbose_name='Participant type name')),
                ('order', models.JSONField()),
                ('costs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.costs')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ticket')),
            ],
            options={
                'verbose_name': 'ParticipantType',
                'verbose_name_plural': 'ParticipantTypes',
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
    ]
