# Generated by Django 3.2.17 on 2023-03-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_raffle_has_been_held'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_payment',
            field=models.FloatField(default=0, help_text='Price to be paid by participant(s)', verbose_name='Total payment'),
        ),
    ]
