# Generated by Django 3.2.3 on 2021-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20211125_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_participants_per_ticket',
            field=models.IntegerField(default=1, help_text="This dictates the number of participants that each ticket entry allows. For example, the puzzle hunt rally would want this to be 9. Don't set this to be less than 1.", verbose_name='Number of participants per ticket'),
        ),
    ]
