# Generated by Django 3.2.17 on 2023-08-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_ticket_total_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='base_price_nonmember',
            field=models.IntegerField(default=0, help_text='Base ticket price for non-members.', verbose_name='Ticket price for non-members'),
        ),
    ]
