# Generated by Django 3.2.3 on 2021-11-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20211130_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='order',
            field=models.JSONField(default=dict),
        ),
    ]
