# Generated by Django 3.2.3 on 2021-11-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_participant_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='person_nr',
            field=models.CharField(default=None, help_text='Person number using the YYYYMMDD-XXXX format.', max_length=13, verbose_name='Person number'),
            preserve_default=False,
        ),
    ]
