# Generated by Django 2.2.2 on 2019-11-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0009_auto_20181229_0326'),
        ('google', '0012_auto_20181001_1949'),
    ]

    operations = [
    ]
