# Generated by Django 2.2.10 on 2020-04-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0017_auto_20200404_2152'),
        ('google', '0024_auto_20200404_1628'),
    ]

    operations = [
    ]
