# Generated by Django 3.1.2 on 2020-10-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0026_auto_20201023_1517'),
        ('google', '0026_auto_20201023_1815'),
    ]

    operations = [
    ]
