# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 12:49
from __future__ import unicode_literals

from django.db import migrations
# TODO: Remove migration folders

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='logo_black',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='logo_white',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
