# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('person_number_ext', models.CharField(blank=True, help_text='Enter the last four digits of your Swedish person number, given by the Swedish tax authority', max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='The person number extension consists of four numbers', regex='^\\d{10}$')], verbose_name='Person number extension')),
                ('phone_number', models.CharField(blank=True, help_text='Enter a phone number so UTN may reach you', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?\\d+$')], verbose_name='Phone number')),
                ('registration_year', models.CharField(blank=True, help_text='Enter the year you started studying at the TakNat faculty', max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid year', regex='^\\d{4}$')], verbose_name='Registration year')),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the study program', max_length=255, verbose_name='Study program name')),
                ('name_en', models.CharField(help_text='Enter the name of the study program', max_length=255, null=True, verbose_name='Study program name')),
                ('name_sv', models.CharField(help_text='Enter the name of the study program', max_length=255, null=True, verbose_name='Study program name')),
                ('abbreviation', models.CharField(blank=True, help_text='Enter the abbreviation for the study program', max_length=130, null=True, verbose_name='Study program abbreviation')),
                ('abbreviation_en', models.CharField(blank=True, help_text='Enter the abbreviation for the study program', max_length=130, null=True, verbose_name='Study program abbreviation')),
                ('abbreviation_sv', models.CharField(blank=True, help_text='Enter the abbreviation for the study program', max_length=130, null=True, verbose_name='Study program abbreviation')),
                ('degree', models.CharField(choices=[('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('engineer', "Engineer's Degree")], max_length=20, verbose_name='Degree type')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.StudyProgram'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
