# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title_en', models.CharField(blank=True, help_text='Enter the title to be shown on the banner.', max_length=255, verbose_name='English banner title')),
                ('title_sv', models.CharField(blank=True, help_text='Enter the title to be shown on the banner.', max_length=255, verbose_name='Swedish banner title')),
                ('text_en', models.TextField(blank=True, help_text='Enter a text to be shown on the banner.', verbose_name='English banner text')),
                ('text_sv', models.TextField(blank=True, help_text='Enter a text to be shown on the banner.', verbose_name='Swedish banner text')),
                ('link', models.URLField(blank=True, verbose_name='Button URL')),
                ('button_en', models.TextField(blank=True, help_text='Enter the text to be displayed on the button.', verbose_name='English button text')),
                ('button_sv', models.TextField(blank=True, help_text='Enter the text to be displayed on the button.', verbose_name='Swedish button text')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
