# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('home', '0008_auto_20170712_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_sv', models.CharField(max_length=255)),
                ('contact_point_en', wagtail.wagtailcore.fields.StreamField((('person', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('name', wagtail.wagtailcore.blocks.CharBlock()), ('role', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('description', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('email', wagtail.wagtailcore.blocks.EmailBlock(required=False))))),))),
                ('contact_point_sv', wagtail.wagtailcore.fields.StreamField((('person', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('name', wagtail.wagtailcore.blocks.CharBlock()), ('role', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('description', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('email', wagtail.wagtailcore.blocks.EmailBlock(required=False))))),))),
                ('other_contacts_en', wagtail.wagtailcore.fields.StreamField((('contact', wagtail.wagtailcore.blocks.StructBlock((('person', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('name', wagtail.wagtailcore.blocks.CharBlock()), ('role', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('description', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('email', wagtail.wagtailcore.blocks.EmailBlock(required=False))))), ('group', wagtail.wagtailcore.blocks.CharBlock(required=False))), icon='user')),))),
                ('other_contacts_sv', wagtail.wagtailcore.fields.StreamField((('contact', wagtail.wagtailcore.blocks.StructBlock((('person', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('name', wagtail.wagtailcore.blocks.CharBlock()), ('role', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('description', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('email', wagtail.wagtailcore.blocks.EmailBlock(required=False))))), ('group', wagtail.wagtailcore.blocks.CharBlock(required=False))), icon='user')),))),
                ('map_location', models.CharField(blank=True, help_text='Enter comma separated coordinates', max_length=255, verbose_name='Map Location')),
                ('location_description', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Enter the text to show on the map', verbose_name='Location Description')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
